export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: string;
  model: string;
  category: string;
  subcategory?: string | null;
  price: number;
  discountPrice?: number | null;
  inStock: boolean;
  voltage: string;
  capacity: string;
  cca?: string | null;
  batteryType: string;
  dimensions?: string | null;
  weight?: string | null;
  terminalType?: string | null;
  application?: string | null;
  warranty?: string | null;
  compatibilityNotes?: string | null;
  manufacturer?: string | null;
  countryOfOrigin?: string | null;
  isFeatured: boolean;
  isPublished: boolean;
  sku: string;
  description: string;
  images: string[];
}

export const PRODUCTS: Product[] = [
  {
    "slug": "energy-man-pro-75ah-car-battery",
    "name": "ENERGY MAN Pro 75Ah Maintenance-Free Car Battery",
    "brand": "ENERGY MAN",
    "model": "EM-AUTO-75MF",
    "category": "automotive",
    "subcategory": "Car Batteries",
    "price": 68000,
    "discountPrice": 62000,
    "voltage": "12V",
    "capacity": "75Ah",
    "cca": "650 CCA",
    "batteryType": "Sealed Maintenance-Free (Calcium-Calcium)",
    "dimensions": "278 x 175 x 190 mm",
    "weight": "17.8 kg",
    "terminalType": "Standard DIN Terminal (A)",
    "application": "Sedans, SUVs, Toyota Camry, Honda Accord, Lexus RX, Hyundai Sonata",
    "warranty": "12 Months",
    "compatibilityNotes": "Fits most Japanese, Korean and European passenger vehicles requiring 65-75Ah capacity.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-AUTO-001",
    "description": "The ENERGY MAN Pro 75Ah delivers high cold-cranking power and long service life engineered for Nigerian road and weather conditions. Sealed maintenance-free design with heavy-duty lead grid plates and built-in magic-eye state-of-charge indicator.",
    "id": "em-automotive-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-auto-1.jpg",
      "/images/prod-auto-2.jpg"
    ]
  },
  {
    "slug": "energy-man-heavy-start-100ah-suv-battery",
    "name": "ENERGY MAN Heavy-Start 100Ah SUV & Commercial Battery",
    "brand": "ENERGY MAN",
    "model": "EM-AUTO-100MF",
    "category": "automotive",
    "subcategory": "SUV Batteries",
    "price": 95000,
    "voltage": "12V",
    "capacity": "100Ah",
    "cca": "820 CCA",
    "batteryType": "Sealed Maintenance-Free Lead Acid",
    "dimensions": "353 x 175 x 190 mm",
    "weight": "23.5 kg",
    "terminalType": "Standard SAE Post",
    "application": "Toyota Land Cruiser, Prado, Hilux, Ford Ranger, Mercedes G-Class, Commercial Vans",
    "warranty": "12 Months",
    "compatibilityNotes": "Designed for heavy power demands, big V6/V8 diesel and petrol engines, and vehicles with high electronic accessories.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-AUTO-002",
    "description": "Engineered for high-power SUVs, pick-up trucks and light commercial vans. Provides maximum reserve capacity for extra lights, sound systems and air conditioning equipment.",
    "id": "em-automotive-002",
    "discountPrice": null,
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-auto-2.jpg",
      "/images/prod-auto-5.jpg"
    ]
  },
  {
    "slug": "chloride-exide-ultra-60ah-car-battery",
    "name": "Chloride Exide Ultra 60Ah Passenger Car Battery",
    "brand": "Chloride Exide",
    "model": "CE-60MF-L",
    "category": "automotive",
    "subcategory": "Car Batteries",
    "price": 55000,
    "discountPrice": 51000,
    "voltage": "12V",
    "capacity": "60Ah",
    "cca": "510 CCA",
    "batteryType": "Sealed Calcium",
    "dimensions": "242 x 175 x 190 mm",
    "weight": "14.2 kg",
    "terminalType": "Standard DIN",
    "application": "Compact Cars, Hatchbacks, Toyota Corolla, Honda Civic, Kia Rio",
    "warranty": "12 Months",
    "compatibilityNotes": "Ideal for 1.3L to 2.0L engines.",
    "manufacturer": "Chloride Exide",
    "countryOfOrigin": "Kenya",
    "sku": "CE-AUTO-003",
    "description": "A trusted name in Nigerian motoring — reliable starting power, low water loss and dependable performance for daily commuters and small family cars.",
    "id": "em-automotive-003",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-auto-5.jpg",
      "/images/cat-automotive.jpg"
    ]
  },
  {
    "slug": "energy-man-start-stop-agm-80ah-battery",
    "name": "ENERGY MAN Start-Stop AGM 80Ah Car Battery",
    "brand": "ENERGY MAN",
    "model": "EM-AGM-80",
    "category": "automotive",
    "subcategory": "Car Batteries",
    "price": 110000,
    "discountPrice": 102000,
    "voltage": "12V",
    "capacity": "80Ah",
    "cca": "800 CCA",
    "batteryType": "AGM (Absorbent Glass Mat)",
    "dimensions": "315 x 175 x 190 mm",
    "weight": "21.0 kg",
    "terminalType": "Standard DIN",
    "application": "Start-Stop Vehicles, Mercedes C-Class, BMW 3 Series, Audi A4, Toyota Camry Hybrid",
    "warranty": "24 Months",
    "compatibilityNotes": "Required for vehicles with start-stop systems and regenerative braking.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-AUTO-004",
    "description": "True AGM technology for modern start-stop vehicles. Three times the cycle life of standard batteries, spill-proof and vibration resistant.",
    "id": "em-automotive-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-automotive.jpg",
      "/images/prod-auto-1.jpg"
    ]
  },
  {
    "slug": "energy-man-cruiser-45ah-car-battery",
    "name": "ENERGY MAN Cruiser 45Ah Small Car Battery",
    "brand": "ENERGY MAN",
    "model": "EM-AUTO-45MF",
    "category": "automotive",
    "subcategory": "Car Batteries",
    "price": 42000,
    "discountPrice": 38000,
    "voltage": "12V",
    "capacity": "45Ah",
    "cca": "430 CCA",
    "batteryType": "Sealed Maintenance-Free",
    "dimensions": "212 x 175 x 190 mm",
    "weight": "11.5 kg",
    "terminalType": "Standard DIN",
    "application": "Toyota Yaris, Nissan Micra, Hyundai i10, Kia Picanto, small sedans",
    "warranty": "12 Months",
    "compatibilityNotes": "Perfect for small-engine city cars up to 1.5L.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-AUTO-005",
    "description": "Compact, dependable power for small cars. Quick-recovery calcium plates handle the stop-and-go of city driving with ease.",
    "id": "em-automotive-005",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-auto-1.jpg",
      "/images/prod-auto-2.jpg"
    ]
  },
  {
    "slug": "chloride-exide-power-65ah-car-battery",
    "name": "Chloride Exide Power 65Ah Car Battery",
    "brand": "Chloride Exide",
    "model": "CE-65MF",
    "category": "automotive",
    "subcategory": "Car Batteries",
    "price": 62500,
    "discountPrice": 58000,
    "voltage": "12V",
    "capacity": "65Ah",
    "cca": "580 CCA",
    "batteryType": "Sealed Calcium Maintenance-Free",
    "dimensions": "261 x 175 x 190 mm",
    "weight": "15.6 kg",
    "terminalType": "Standard DIN",
    "application": "Toyota Corolla, Honda CR-V, Nissan Sentra, Kia Cerato",
    "warranty": "12 Months",
    "compatibilityNotes": "A direct-fit upgrade for cars originally fitted with 55-65Ah batteries.",
    "manufacturer": "Chloride Exide",
    "countryOfOrigin": "Kenya",
    "sku": "CE-AUTO-006",
    "description": "Balanced power and value for mid-size saloons. Exide calcium technology reduces water loss and extends service life in hot climates.",
    "id": "em-automotive-006",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-auto-2.jpg",
      "/images/prod-auto-5.jpg"
    ]
  },
  {
    "slug": "energy-man-heavy-start-90ah-van-battery",
    "name": "ENERGY MAN Heavy-Start 90Ah Hiace & Van Battery",
    "brand": "ENERGY MAN",
    "model": "EM-AUTO-90MF",
    "category": "automotive",
    "subcategory": "SUV Batteries",
    "price": 88000,
    "voltage": "12V",
    "capacity": "90Ah",
    "cca": "760 CCA",
    "batteryType": "Sealed Maintenance-Free Lead Acid",
    "dimensions": "330 x 175 x 220 mm",
    "weight": "22.0 kg",
    "terminalType": "Standard SAE Post",
    "application": "Toyota Hiace, Nissan Urvan, commuter buses, delivery vans",
    "warranty": "12 Months",
    "compatibilityNotes": "Extra vibration resistance for commercial transport duty cycles.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-AUTO-007",
    "description": "Built for the daily grind of commercial passenger and delivery vehicles — heavy plates, high cranking power and dependable all-day service.",
    "id": "em-automotive-007",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-auto-5.jpg",
      "/images/cat-automotive.jpg"
    ]
  },
  {
    "slug": "energy-man-rider-ytx9-bs-motorcycle-battery",
    "name": "ENERGY MAN Rider YTX9-BS Motorcycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-YTX9BS",
    "category": "motorcycle",
    "subcategory": "Motorcycle Batteries",
    "price": 22000,
    "discountPrice": 19500,
    "voltage": "12V",
    "capacity": "9Ah",
    "cca": "135 CCA",
    "batteryType": "Sealed Maintenance-Free (AGM)",
    "dimensions": "150 x 87 x 105 mm",
    "weight": "3.2 kg",
    "terminalType": "Universal PTZ",
    "application": "Honda CG125, Bajaj Boxer, TVS Star, Yamaha CRX",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-MOTO-001",
    "description": "Sealed AGM power for popular Nigerian motorcycles. Ships charged and ready — no acid filling required, just install and ride.",
    "id": "em-motorcycle-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/cat-motorcycle.jpg",
      "/images/prod-moto-2.jpg"
    ]
  },
  {
    "slug": "energy-man-12v-14ah-tricycle-keke-battery",
    "name": "ENERGY MAN 12V 14Ah Tricycle (Keke) Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-14A",
    "category": "motorcycle",
    "subcategory": "Tricycle Batteries",
    "price": 26000,
    "discountPrice": 23500,
    "voltage": "12V",
    "capacity": "14Ah",
    "cca": "200 CCA",
    "batteryType": "Sealed Maintenance-Free",
    "dimensions": "134 x 133 x 166 mm",
    "weight": "4.0 kg",
    "terminalType": "Universal PTZ",
    "application": "Keke Napep tricycles, Bajaj RE, TVS King",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-002",
    "description": "Purpose-built for keke tricycles. High cranking current for start-and-stop commercial routes and electric starters.",
    "id": "em-motorcycle-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-moto-2.jpg",
      "/images/cat-motorcycle.jpg"
    ]
  },
  {
    "slug": "energy-man-rider-yb4l-scooter-battery",
    "name": "ENERGY MAN Rider YB4L Scooter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-YB4L",
    "category": "motorcycle",
    "subcategory": "Motorcycle Batteries",
    "price": 15500,
    "voltage": "12V",
    "capacity": "4Ah",
    "cca": "70 CCA",
    "batteryType": "Conventional Flooded",
    "dimensions": "120 x 70 x 92 mm",
    "weight": "1.6 kg",
    "terminalType": "Universal PTZ",
    "application": "Small scooters, mopeds, Jincheng bikes",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-003",
    "description": "Lightweight, affordable backup power for small scooters and mopeds. Comes dry-charged with acid pack.",
    "id": "em-motorcycle-003",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-motorcycle.jpg",
      "/images/prod-moto-2.jpg"
    ]
  },
  {
    "slug": "energy-man-rider-yb7c-motorcycle-battery",
    "name": "ENERGY MAN Rider YB7C Motorcycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-YB7C",
    "category": "motorcycle",
    "subcategory": "Motorcycle Batteries",
    "price": 19500,
    "voltage": "12V",
    "capacity": "7Ah",
    "cca": "105 CCA",
    "batteryType": "Conventional Flooded",
    "dimensions": "137 x 77 x 135 mm",
    "weight": "2.5 kg",
    "terminalType": "Universal PTZ",
    "application": "Suzuki AX100, Jianshe, Qingqi motorcycles",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-004",
    "description": "A workhorse battery for everyday 100-125cc motorcycles. Easy to service and widely available replacement.",
    "id": "em-motorcycle-004",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-moto-2.jpg",
      "/images/cat-motorcycle.jpg"
    ]
  },
  {
    "slug": "energy-man-rider-ytz10s-motorcycle-battery",
    "name": "ENERGY MAN Rider YTZ10S Sealed Motorcycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-YTZ10S",
    "category": "motorcycle",
    "subcategory": "Motorcycle Batteries",
    "price": 28000,
    "discountPrice": 25500,
    "voltage": "12V",
    "capacity": "8.6Ah",
    "cca": "150 CCA",
    "batteryType": "Sealed AGM Maintenance-Free",
    "dimensions": "150 x 87 x 105 mm",
    "weight": "3.4 kg",
    "terminalType": "Universal PTZ",
    "application": "Honda CB series, power bikes, sport motorcycles, big generators",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-005",
    "description": "Premium sealed battery for power bikes and high-displacement motorcycles. Superior vibration resistance and long shelf life.",
    "id": "em-motorcycle-005",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-motorcycle.jpg",
      "/images/prod-moto-2.jpg"
    ]
  },
  {
    "slug": "energy-man-keke-max-18ah-tricycle-battery",
    "name": "ENERGY MAN Keke Max 18Ah Heavy-Duty Tricycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-18HD",
    "category": "motorcycle",
    "subcategory": "Tricycle Batteries",
    "price": 34000,
    "voltage": "12V",
    "capacity": "18Ah",
    "cca": "260 CCA",
    "batteryType": "Sealed Maintenance-Free",
    "dimensions": "181 x 77 x 170 mm",
    "weight": "5.2 kg",
    "terminalType": "Universal PTZ",
    "application": "Heavy tricycles, Keke with sound systems and extra lights",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-006",
    "description": "Extra capacity for tricycle operators running horns, music and lighting. Longer cranking reserve and heavy-duty plates.",
    "id": "em-motorcycle-006",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-moto-2.jpg",
      "/images/cat-motorcycle.jpg"
    ]
  },
  {
    "slug": "energy-man-rider-ytx12-bs-motorcycle-battery",
    "name": "ENERGY MAN Rider YTX12-BS Sports Bike Battery",
    "brand": "ENERGY MAN",
    "model": "EM-MOTO-YTX12BS",
    "category": "motorcycle",
    "subcategory": "Motorcycle Batteries",
    "price": 31000,
    "discountPrice": 28000,
    "voltage": "12V",
    "capacity": "10Ah",
    "cca": "185 CCA",
    "batteryType": "Sealed AGM Maintenance-Free",
    "dimensions": "150 x 87 x 131 mm",
    "weight": "4.0 kg",
    "terminalType": "Universal PTZ",
    "application": "Yamaha, Kawasaki, Suzuki sports bikes, cruisers",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-MOTO-007",
    "description": "High-cranking sealed AGM battery for sports bikes and cruisers. Factory-activated, spill-proof and ready to install.",
    "id": "em-motorcycle-007",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-motorcycle.jpg",
      "/images/prod-moto-2.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-150ah-truck-battery",
    "name": "ENERGY MAN Titan 150Ah Truck Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-150",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 260000,
    "discountPrice": 245000,
    "voltage": "12V",
    "capacity": "150Ah",
    "cca": "950 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "513 x 223 x 220 mm",
    "weight": "38.5 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Sinotruk Howo, Shacman, Mercedes Axor, MAN trucks",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-TRK-001",
    "description": "Serious cranking power for rig engines. Thick-plate construction handles deep engine bays, long hauls and heavy vibration.",
    "id": "em-truck-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-truck-1.jpg",
      "/images/cat-truck.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-max-200ah-heavy-duty-battery",
    "name": "ENERGY MAN Titan Max 200Ah Heavy-Duty Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-200",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 380000,
    "discountPrice": 355000,
    "voltage": "12V",
    "capacity": "200Ah",
    "cca": "1200 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "518 x 276 x 250 mm",
    "weight": "52.0 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Heavy trucks, trailers, tippers, DAF, Volvo FH",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TRK-002",
    "description": "Maximum power for the biggest diesel engines. Exceptional reserve capacity for tippers, trailers and long-haul fleets.",
    "id": "em-truck-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-truck.jpg",
      "/images/prod-truck-1.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-120ah-truck-battery",
    "name": "ENERGY MAN Titan 120Ah Medium Truck Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-120",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 210000,
    "voltage": "12V",
    "capacity": "120Ah",
    "cca": "850 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "513 x 189 x 223 mm",
    "weight": "32.0 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Mitsubishi Fuso, Isuzu NPR, medium-duty trucks and buses",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TRK-003",
    "description": "Dependable starting power for medium-duty trucks and minibuses. Vibration-resistant plates built for Nigerian roads.",
    "id": "em-truck-003",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-truck-1.jpg",
      "/images/cat-truck.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-hd-180ah-truck-battery",
    "name": "ENERGY MAN Titan HD 180Ah Truck Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-180",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 330000,
    "voltage": "12V",
    "capacity": "180Ah",
    "cca": "1100 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "518 x 276 x 250 mm",
    "weight": "47.5 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Heavy trucks, bulldozers, excavators, generators",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TRK-004",
    "description": "High-output power for construction equipment and heavy generators. Extra-thick grids resist vibration and deep discharge.",
    "id": "em-truck-004",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-truck.jpg",
      "/images/prod-truck-1.jpg"
    ]
  },
  {
    "slug": "chloride-exide-commercial-140ah-battery",
    "name": "Chloride Exide Commercial 140Ah Truck Battery",
    "brand": "Chloride Exide",
    "model": "CE-TRK-140",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 245000,
    "discountPrice": 228000,
    "voltage": "12V",
    "capacity": "140Ah",
    "cca": "900 CCA",
    "batteryType": "Heavy-Duty Maintenance-Capable",
    "dimensions": "513 x 223 x 220 mm",
    "weight": "36.0 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Medium and heavy trucks, commercial buses",
    "warranty": "12 Months",
    "manufacturer": "Chloride Exide",
    "countryOfOrigin": "Kenya",
    "sku": "CE-TRK-005",
    "description": "Proven commercial-duty battery from a brand Nigerian transporters have trusted for decades.",
    "id": "em-truck-005",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-truck-1.jpg",
      "/images/cat-truck.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-genset-100ah-battery",
    "name": "ENERGY MAN Titan Genset 100Ah Generator Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-GEN100",
    "category": "truck",
    "subcategory": "Generator Batteries",
    "price": 150000,
    "discountPrice": 138000,
    "voltage": "12V",
    "capacity": "100Ah",
    "cca": "820 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "353 x 175 x 190 mm",
    "weight": "24.5 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Industrial generator sets — Perkins, FG Wilson, Mikano",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TRK-006",
    "description": "Cranking power for diesel generator sets. Built to deliver reliable starts on demand for standby and prime power gensets.",
    "id": "em-truck-006",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-truck.jpg",
      "/images/prod-truck-1.jpg"
    ]
  },
  {
    "slug": "energy-man-titan-bus-220ah-battery",
    "name": "ENERGY MAN Titan Bus 220Ah Heavy-Duty Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TRK-220",
    "category": "truck",
    "subcategory": "Truck Batteries",
    "price": 420000,
    "voltage": "12V",
    "capacity": "220Ah",
    "cca": "1300 CCA",
    "batteryType": "Heavy-Duty Flooded Lead Acid",
    "dimensions": "518 x 293 x 276 mm",
    "weight": "58.0 kg",
    "terminalType": "Heavy SAE Post",
    "application": "Luxury buses, BRT buses, coach fleets",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TRK-007",
    "description": "Flagship capacity for coach and BRT fleets. Delivers dependable starts with heavy electrical loads — air conditioning, lighting and doors.",
    "id": "em-truck-007",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-truck-1.jpg",
      "/images/cat-truck.jpg"
    ]
  },
  {
    "slug": "energy-man-solarpro-220ah-tall-tubular-battery",
    "name": "ENERGY MAN SolarPro 220Ah Tall Tubular Solar Battery",
    "brand": "ENERGY MAN",
    "model": "EM-SOL-220T",
    "category": "solar",
    "subcategory": "Tubular Solar Batteries",
    "price": 320000,
    "discountPrice": 295000,
    "voltage": "12V",
    "capacity": "220Ah",
    "batteryType": "Tall Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "58.5 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Home solar systems, 2kVA-5kVA inverters, hybrid solar setups",
    "warranty": "24 Months",
    "compatibilityNotes": "Requires deep-cycle charge controller settings for best life.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-SOL-001",
    "description": "Deep-cycle tubular plates engineered for daily solar charge and discharge. Long life, low maintenance and high sustained capacity.",
    "id": "em-solar-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-solar-1.jpg",
      "/images/prod-solar-2.jpg"
    ]
  },
  {
    "slug": "sonnenschein-solar-gel-200ah-battery",
    "name": "Sonnenschein Solar Gel 200Ah Deep-Cycle Battery",
    "brand": "Sonnenschein",
    "model": "SS-GEL-200",
    "category": "solar",
    "subcategory": "Gel Solar Batteries",
    "price": 410000,
    "discountPrice": 385000,
    "voltage": "12V",
    "capacity": "200Ah",
    "batteryType": "Gel Deep-Cycle Sealed",
    "dimensions": "522 x 240 x 220 mm",
    "weight": "55.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Premium solar systems, off-grid homes, telecom solar sites",
    "warranty": "24 Months",
    "compatibilityNotes": "Sealed gel — zero maintenance, safe for indoor installation.",
    "manufacturer": "Sonnenschein (GNB Industrial Power)",
    "countryOfOrigin": "Germany",
    "sku": "SS-SOL-002",
    "description": "German gel technology for premium off-grid systems. Completely sealed, maintenance-free and extremely deep-cycle capable.",
    "id": "em-solar-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-solar-2.jpg",
      "/images/cat-solar.jpg"
    ]
  },
  {
    "slug": "energy-man-solarpro-150ah-tubular-battery",
    "name": "ENERGY MAN SolarPro 150Ah Tubular Solar Battery",
    "brand": "ENERGY MAN",
    "model": "EM-SOL-150T",
    "category": "solar",
    "subcategory": "Tubular Solar Batteries",
    "price": 180000,
    "discountPrice": 168000,
    "voltage": "12V",
    "capacity": "150Ah",
    "batteryType": "Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "43.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "1kVA-2.5kVA solar systems, small home setups",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-SOL-003",
    "description": "The dependable workhorse of Nigerian home solar. Tubular plates deliver long daily cycles at an affordable price.",
    "id": "em-solar-003",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-solar.jpg",
      "/images/prod-solar-1.jpg"
    ]
  },
  {
    "slug": "energy-man-solarpro-100ah-tubular-battery",
    "name": "ENERGY MAN SolarPro 100Ah Tubular Solar Battery",
    "brand": "ENERGY MAN",
    "model": "EM-SOL-100T",
    "category": "solar",
    "subcategory": "Tubular Solar Batteries",
    "price": 120000,
    "discountPrice": 112000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "32.5 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Small solar setups, street lights, CCTV systems",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-SOL-004",
    "description": "Entry-level deep-cycle tubular power for small solar installations, street lights and security systems.",
    "id": "em-solar-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-solar-1.jpg",
      "/images/prod-solar-2.jpg"
    ]
  },
  {
    "slug": "felicity-solar-200ah-gel-battery",
    "name": "Felicity Solar 200Ah Gel Deep-Cycle Battery",
    "brand": "Felicity",
    "model": "FL-GEL-200",
    "category": "solar",
    "subcategory": "Gel Solar Batteries",
    "price": 260000,
    "voltage": "12V",
    "capacity": "200Ah",
    "batteryType": "Gel Deep-Cycle Sealed",
    "dimensions": "522 x 240 x 220 mm",
    "weight": "56.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Solar hybrid systems, offices, guest houses",
    "warranty": "18 Months",
    "manufacturer": "Felicity Solar",
    "countryOfOrigin": "China",
    "sku": "FL-SOL-005",
    "description": "Popular gel option for solar users who want sealed convenience at a friendly price. Good deep-cycle performance for daily use.",
    "id": "em-solar-005",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-solar-2.jpg",
      "/images/cat-solar.jpg"
    ]
  },
  {
    "slug": "energy-man-solarpro-250ah-tall-tubular-battery",
    "name": "ENERGY MAN SolarPro 250Ah Tall Tubular Solar Battery",
    "brand": "ENERGY MAN",
    "model": "EM-SOL-250T",
    "category": "solar",
    "subcategory": "Tubular Solar Batteries",
    "price": 380000,
    "voltage": "12V",
    "capacity": "250Ah",
    "batteryType": "Tall Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "65.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Large home solar systems, 5kVA+ inverters",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-SOL-006",
    "description": "Maximum tubular capacity for big solar arrays. Extended backup for homes and businesses that run heavy loads overnight.",
    "id": "em-solar-006",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-solar.jpg",
      "/images/prod-solar-1.jpg"
    ]
  },
  {
    "slug": "fullriver-agm-220ah-deep-cycle-battery",
    "name": "Fullriver AGM 220Ah Sealed Deep-Cycle Battery",
    "brand": "Fullriver",
    "model": "FR-DC220-12",
    "category": "solar",
    "subcategory": "AGM Solar Batteries",
    "price": 350000,
    "discountPrice": 325000,
    "voltage": "12V",
    "capacity": "220Ah",
    "batteryType": "AGM Sealed Deep-Cycle",
    "dimensions": "522 x 240 x 220 mm",
    "weight": "60.0 kg",
    "terminalType": "Stainless Terminal Post",
    "application": "Off-grid solar, marine, telecom, sealed installations",
    "warranty": "18 Months",
    "manufacturer": "Fullriver Battery",
    "countryOfOrigin": "China",
    "sku": "FR-SOL-007",
    "description": "Premium sealed AGM deep-cycle battery. No fumes, no watering — safe for indoor and sensitive installations.",
    "id": "em-solar-007",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-solar-1.jpg",
      "/images/prod-solar-2.jpg"
    ]
  },
  {
    "slug": "energy-man-powerbank-220ah-tubular-battery",
    "name": "ENERGY MAN Powerbank 220Ah Tall Tubular Inverter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-INV-220T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 310000,
    "discountPrice": 288000,
    "voltage": "12V",
    "capacity": "220Ah",
    "batteryType": "Tall Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "58.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Home and office inverters, 2.5kVA-5kVA systems",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-INV-001",
    "description": "The most popular inverter battery size in Nigeria. Long backup through evening and night use, built for daily cycling between grid and inverter power.",
    "id": "em-inverter-001",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-inverter-1.jpg",
      "/images/cat-inverter.jpg"
    ]
  },
  {
    "slug": "exide-inva-tubular-200ah-inverter-battery",
    "name": "Exide Inva Tubular 200Ah Inverter Battery",
    "brand": "Exide",
    "model": "EX-INV-200T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 295000,
    "discountPrice": 272000,
    "voltage": "12V",
    "capacity": "200Ah",
    "batteryType": "Tall Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "54.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Home inverter systems, 2kVA-3.5kVA inverters",
    "warranty": "24 Months",
    "manufacturer": "Exide Industries",
    "countryOfOrigin": "India",
    "sku": "EX-INV-002",
    "description": "Indian tubular engineering with a long track record in Nigerian homes. Reliable deep discharge recovery and long service life.",
    "id": "em-inverter-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-inverter.jpg",
      "/images/prod-inverter-1.jpg"
    ]
  },
  {
    "slug": "energy-man-powerbank-150ah-tubular-battery",
    "name": "ENERGY MAN Powerbank 150Ah Tubular Inverter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-INV-150T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 165000,
    "discountPrice": 155000,
    "voltage": "12V",
    "capacity": "150Ah",
    "batteryType": "Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "41.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Flats, small offices, 1.5kVA-2kVA inverters",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-INV-003",
    "description": "Balanced capacity for smaller homes and offices. Comfortable backup for lights, fans, TV and phones through power cuts.",
    "id": "em-inverter-003",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-inverter-1.jpg",
      "/images/cat-inverter.jpg"
    ]
  },
  {
    "slug": "energy-man-powerbank-100ah-tubular-battery",
    "name": "ENERGY MAN Powerbank 100Ah Tubular Inverter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-INV-100T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 105000,
    "discountPrice": 98000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "31.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Single-room setups, small inverters, POS business backup",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-INV-004",
    "description": "Affordable entry into inverter ownership. Perfect first battery for rooms, shops and small businesses.",
    "id": "em-inverter-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-inverter.jpg",
      "/images/prod-inverter-1.jpg"
    ]
  },
  {
    "slug": "exide-inva-tubular-150ah-battery",
    "name": "Exide Inva Tubular 150Ah Inverter Battery",
    "brand": "Exide",
    "model": "EX-INV-150T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 175000,
    "voltage": "12V",
    "capacity": "150Ah",
    "batteryType": "Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "40.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Home inverter systems, shops, clinics",
    "warranty": "24 Months",
    "manufacturer": "Exide Industries",
    "countryOfOrigin": "India",
    "sku": "EX-INV-005",
    "description": "A mid-range tubular battery from Exide for households that need steady backup at a fair price.",
    "id": "em-inverter-005",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-inverter-1.jpg",
      "/images/cat-inverter.jpg"
    ]
  },
  {
    "slug": "energy-man-backup-gel-180ah-battery",
    "name": "ENERGY MAN Backup Gel 180Ah Sealed Inverter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-INV-G180",
    "category": "inverter",
    "subcategory": "Gel Inverter Batteries",
    "price": 230000,
    "voltage": "12V",
    "capacity": "180Ah",
    "batteryType": "Gel Sealed Deep-Cycle",
    "dimensions": "522 x 240 x 220 mm",
    "weight": "50.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Indoor inverter systems, sealed installations",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-INV-006",
    "description": "Fully sealed gel — no fumes, no topping up. Ideal where batteries live indoors near families and offices.",
    "id": "em-inverter-006",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-inverter.jpg",
      "/images/prod-inverter-1.jpg"
    ]
  },
  {
    "slug": "energy-man-powerbank-250ah-tall-tubular-battery",
    "name": "ENERGY MAN Powerbank 250Ah Tall Tubular Inverter Battery",
    "brand": "ENERGY MAN",
    "model": "EM-INV-250T",
    "category": "inverter",
    "subcategory": "Tubular Inverter Batteries",
    "price": 395000,
    "voltage": "12V",
    "capacity": "250Ah",
    "batteryType": "Tall Tubular Deep-Cycle Flooded",
    "dimensions": "502 x 191 x 410 mm",
    "weight": "65.0 kg",
    "terminalType": "Copper Terminal Post",
    "application": "Large home and office inverters, 5kVA systems",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-INV-007",
    "description": "Top-of-the-line backup capacity. Runs freezers, AC units and offices comfortably through extended outages.",
    "id": "em-inverter-007",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-inverter-1.jpg",
      "/images/cat-inverter.jpg"
    ]
  },
  {
    "slug": "energy-man-lifepo4-48v-100ah-5-12kwh-wall-mount-lithium-battery",
    "name": "ENERGY MAN LiFePO4 48V 100Ah (5.12kWh) Wall-Mount Lithium Battery",
    "brand": "ENERGY MAN",
    "model": "EM-LFP-48-100WM",
    "category": "lithium",
    "subcategory": "Wall-Mount Lithium",
    "price": 1250000,
    "discountPrice": 1150000,
    "voltage": "48V",
    "capacity": "100Ah (5.12kWh)",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "460 x 400 x 160 mm",
    "weight": "43.0 kg",
    "terminalType": "CAN/RS485 Communication Port",
    "application": "Hybrid solar inverters, 48V systems, whole-home backup",
    "warranty": "60 Months (5 Years)",
    "compatibilityNotes": "Compatible with most 48V hybrid inverters (Growatt, Deye, Felicity, Must).",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-LFP-001",
    "description": "Premium LiFePO4 energy storage with built-in BMS. 6000+ cycle life, wall-mount design and smart communication with your inverter. The long-term investment that outlasts lead acid five times over.",
    "id": "em-lithium-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-lithium-1.jpg",
      "/images/prod-lithium-2.jpg"
    ]
  },
  {
    "slug": "energy-man-lifepo4-12v-100ah-lithium-battery",
    "name": "ENERGY MAN LiFePO4 12V 100Ah Lithium Deep-Cycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-LFP-12-100",
    "category": "lithium",
    "subcategory": "12V Lithium",
    "price": 380000,
    "discountPrice": 355000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "330 x 172 x 220 mm",
    "weight": "12.5 kg",
    "terminalType": "M8 Terminal",
    "application": "Solar systems, inverter upgrades, boats, caravans",
    "warranty": "36 Months",
    "compatibilityNotes": "Direct 12V replacement for lead-acid banks — check charger compatibility.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-LFP-002",
    "description": "Featherweight lithium power at one-third the weight of lead acid. Built-in BMS protects against over-charge, over-discharge and short circuit.",
    "id": "em-lithium-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-lithium-2.jpg",
      "/images/cat-lithium.jpg"
    ]
  },
  {
    "slug": "energy-man-lifepo4-24v-100ah-2-56kwh-lithium-battery",
    "name": "ENERGY MAN LiFePO4 24V 100Ah (2.56kWh) Lithium Battery",
    "brand": "ENERGY MAN",
    "model": "EM-LFP-24-100",
    "category": "lithium",
    "subcategory": "24V Lithium",
    "price": 650000,
    "voltage": "24V",
    "capacity": "100Ah (2.56kWh)",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "460 x 400 x 160 mm",
    "weight": "24.0 kg",
    "terminalType": "CAN/RS485 Communication Port",
    "application": "24V solar systems, small hybrid setups",
    "warranty": "60 Months (5 Years)",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-LFP-003",
    "description": "Compact 24V lithium module with smart BMS. Ideal entry into lithium storage for smaller hybrid inverters.",
    "id": "em-lithium-003",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-lithium.jpg",
      "/images/prod-lithium-1.jpg"
    ]
  },
  {
    "slug": "energy-man-lifepo4-12v-200ah-lithium-battery",
    "name": "ENERGY MAN LiFePO4 12V 200Ah Lithium Deep-Cycle Battery",
    "brand": "ENERGY MAN",
    "model": "EM-LFP-12-200",
    "category": "lithium",
    "subcategory": "12V Lithium",
    "price": 520000,
    "discountPrice": 490000,
    "voltage": "12V",
    "capacity": "200Ah",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "522 x 240 x 220 mm",
    "weight": "22.5 kg",
    "terminalType": "M8 Terminal",
    "application": "Large solar banks, trolling motors, off-grid cabins",
    "warranty": "36 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-LFP-004",
    "description": "Serious 12V lithium capacity for big storage banks. Half the weight, double the usable capacity of equivalent tubular batteries.",
    "id": "em-lithium-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-lithium-1.jpg",
      "/images/prod-lithium-2.jpg"
    ]
  },
  {
    "slug": "energy-man-lifepo4-48v-50ah-2-4kwh-lithium-battery",
    "name": "ENERGY MAN LiFePO4 48V 50Ah (2.4kWh) Lithium Battery",
    "brand": "ENERGY MAN",
    "model": "EM-LFP-48-50",
    "category": "lithium",
    "subcategory": "48V Lithium",
    "price": 580000,
    "voltage": "48V",
    "capacity": "50Ah (2.4kWh)",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "460 x 400 x 110 mm",
    "weight": "21.0 kg",
    "terminalType": "CAN/RS485 Communication Port",
    "application": "48V hybrid inverters, starter solar-lithium systems",
    "warranty": "60 Months (5 Years)",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-LFP-005",
    "description": "The starter module for 48V lithium systems. Expandable — add more units later as your power needs grow.",
    "id": "em-lithium-005",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-lithium-2.jpg",
      "/images/cat-lithium.jpg"
    ]
  },
  {
    "slug": "felicity-48v-100ah-rack-lithium-battery",
    "name": "Felicity 48V 100Ah Rack-Mount Lithium Battery",
    "brand": "Felicity",
    "model": "FL-LFP-48-100R",
    "category": "lithium",
    "subcategory": "Rack-Mount Lithium",
    "price": 950000,
    "discountPrice": 890000,
    "voltage": "48V",
    "capacity": "100Ah (5.12kWh)",
    "batteryType": "LiFePO4 Lithium Iron Phosphate",
    "dimensions": "442 x 430 x 132 mm",
    "weight": "40.0 kg",
    "terminalType": "CAN/RS485 Communication Port",
    "application": "Rack solar systems, 48V hybrid inverters",
    "warranty": "60 Months (5 Years)",
    "manufacturer": "Felicity Solar",
    "countryOfOrigin": "China",
    "sku": "FL-LFP-006",
    "description": "Popular rack-mount lithium module. Stack multiple units in a cabinet for scalable storage with smart BMS communication.",
    "id": "em-lithium-006",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-lithium.jpg",
      "/images/prod-lithium-1.jpg"
    ]
  },
  {
    "slug": "energy-man-lithium-home-5kwh-ess",
    "name": "ENERGY MAN LiHome 5kWh Home Energy Storage System",
    "brand": "ENERGY MAN",
    "model": "EM-ESS-5K",
    "category": "lithium",
    "subcategory": "Home ESS",
    "price": 1150000,
    "discountPrice": 1080000,
    "voltage": "48V",
    "capacity": "100Ah (5.12kWh)",
    "batteryType": "LiFePO4 All-in-One ESS",
    "dimensions": "500 x 400 x 160 mm",
    "weight": "45.0 kg",
    "terminalType": "CAN/RS485 Communication Port",
    "application": "Complete home backup — battery, smart BMS and WiFi monitoring",
    "warranty": "60 Months (5 Years)",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-LFP-007",
    "description": "All-in-one home energy storage with app monitoring. Pairs with your hybrid inverter for silent, fume-free power day and night.",
    "id": "em-lithium-007",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-lithium-1.jpg",
      "/images/prod-lithium-2.jpg"
    ]
  },
  {
    "slug": "energy-man-telecom-12v-100ah-front-terminal-battery",
    "name": "ENERGY MAN Telecom 12V 100Ah Front-Terminal Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TEL-100FT",
    "category": "industrial",
    "subcategory": "Telecom Batteries",
    "price": 210000,
    "discountPrice": 198000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "Front-Terminal VRLA AGM",
    "dimensions": "557 x 125 x 316 mm",
    "weight": "30.0 kg",
    "terminalType": "Front Copper Terminals",
    "application": "Telecom towers, BTS sites, UPS systems",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TEL-001",
    "description": "Front-terminal VRLA battery designed for telecom cabinets and racks. Maintenance-free AGM with easy front access for dense installations.",
    "id": "em-industrial-001",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-industrial-2.jpg",
      "/images/cat-industrial.jpg"
    ]
  },
  {
    "slug": "energy-man-ups-12v-12ah-sealed-battery",
    "name": "ENERGY MAN UPS 12V 12Ah Sealed Lead-Acid Battery",
    "brand": "ENERGY MAN",
    "model": "EM-UPS-12-12",
    "category": "industrial",
    "subcategory": "UPS Batteries",
    "price": 18500,
    "discountPrice": 17000,
    "voltage": "12V",
    "capacity": "12Ah",
    "batteryType": "Sealed VRLA",
    "dimensions": "151 x 98 x 97 mm",
    "weight": "4.0 kg",
    "terminalType": "F1/F2 Faston",
    "application": "Home and office UPS units, alarm systems, POS machines",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-UPS-002",
    "description": "Replacement battery for small UPS units and backup devices. Sealed, spill-proof and shipped charged.",
    "id": "em-industrial-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-industrial.jpg",
      "/images/prod-industrial-2.jpg"
    ]
  },
  {
    "slug": "energy-man-telecom-12v-150ah-front-terminal-battery",
    "name": "ENERGY MAN Telecom 12V 150Ah Front-Terminal Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TEL-150FT",
    "category": "industrial",
    "subcategory": "Telecom Batteries",
    "price": 320000,
    "voltage": "12V",
    "capacity": "150Ah",
    "batteryType": "Front-Terminal VRLA AGM",
    "dimensions": "557 x 125 x 316 mm",
    "weight": "44.0 kg",
    "terminalType": "Front Copper Terminals",
    "application": "Telecom sites, data cabinets, industrial UPS",
    "warranty": "24 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TEL-003",
    "description": "Extended-capacity front-terminal battery for high-availability telecom and data installations.",
    "id": "em-industrial-003",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-industrial-2.jpg",
      "/images/cat-industrial.jpg"
    ]
  },
  {
    "slug": "energy-man-ups-12v-7ah-battery",
    "name": "ENERGY MAN UPS 12V 7Ah Sealed Battery",
    "brand": "ENERGY MAN",
    "model": "EM-UPS-12-7",
    "category": "industrial",
    "subcategory": "UPS Batteries",
    "price": 12500,
    "discountPrice": 11500,
    "voltage": "12V",
    "capacity": "7Ah",
    "batteryType": "Sealed VRLA",
    "dimensions": "151 x 65 x 94 mm",
    "weight": "2.4 kg",
    "terminalType": "F1/F2 Faston",
    "application": "Small UPS, CCTV DVRs, alarm panels, intercoms",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-UPS-004",
    "description": "The standard 12V 7Ah replacement for home UPS, CCTV and security systems. Drop-in fit for most devices.",
    "id": "em-industrial-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-industrial.jpg",
      "/images/prod-industrial-2.jpg"
    ]
  },
  {
    "slug": "energy-man-ups-12v-100ah-battery",
    "name": "ENERGY MAN UPS 12V 100Ah Industrial Battery",
    "brand": "ENERGY MAN",
    "model": "EM-UPS-12-100",
    "category": "industrial",
    "subcategory": "UPS Batteries",
    "price": 145000,
    "discountPrice": 135000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "VRLA AGM Deep-Cycle",
    "dimensions": "407 x 173 x 210 mm",
    "weight": "28.0 kg",
    "terminalType": "M6 Insert",
    "application": "Server-room UPS banks, medical equipment backup",
    "warranty": "18 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-UPS-005",
    "description": "Reliable AGM power for server rooms and critical equipment. Low internal resistance for fast UPS response.",
    "id": "em-industrial-005",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-industrial-2.jpg",
      "/images/cat-industrial.jpg"
    ]
  },
  {
    "slug": "quanta-12v-100ah-ups-battery",
    "name": "Quanta 12V 100Ah UPS Battery",
    "brand": "Quanta",
    "model": "QT-12100",
    "category": "industrial",
    "subcategory": "UPS Batteries",
    "price": 135000,
    "voltage": "12V",
    "capacity": "100Ah",
    "batteryType": "VRLA AGM",
    "dimensions": "407 x 173 x 210 mm",
    "weight": "27.5 kg",
    "terminalType": "M6 Insert",
    "application": "UPS systems, banks, data centres, hospitals",
    "warranty": "18 Months",
    "manufacturer": "Quanta Battery",
    "countryOfOrigin": "India",
    "sku": "QT-UPS-006",
    "description": "Trusted UPS battery for Nigerian banks and data rooms. Consistent float service and strong high-rate discharge performance.",
    "id": "em-industrial-006",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-industrial.jpg",
      "/images/prod-industrial-2.jpg"
    ]
  },
  {
    "slug": "energy-man-telecom-2v-500ah-cell-battery",
    "name": "ENERGY MAN Telecom 2V 500Ah Cell Battery",
    "brand": "ENERGY MAN",
    "model": "EM-TEL-2-500",
    "category": "industrial",
    "subcategory": "Telecom Batteries",
    "price": 850000,
    "voltage": "2V",
    "capacity": "500Ah",
    "batteryType": "VRLA Tubular Gel Cell",
    "dimensions": "202 x 118 x 365 mm",
    "weight": "34.0 kg",
    "terminalType": "Copper Cell Post",
    "application": "Large telecom plants, utility substations, 48V cell banks",
    "warranty": "36 Months",
    "compatibilityNotes": "Sold per cell — configure as 24-cell (48V) banks for telecom plants.",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-TEL-007",
    "description": "Industrial-grade 2V cells for mission-critical telecom and utility installations. 20-year design life in float service.",
    "id": "em-industrial-007",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-industrial-2.jpg",
      "/images/cat-industrial.jpg"
    ]
  },
  {
    "slug": "energy-man-intelligent-12v-24v-battery-charger",
    "name": "ENERGY MAN Intelligent 12V/24V Battery Charger",
    "brand": "ENERGY MAN",
    "model": "EM-CHG-1240",
    "category": "accessories",
    "subcategory": "Chargers",
    "price": 65000,
    "discountPrice": 58000,
    "voltage": "12V/24V",
    "capacity": "40A Output",
    "batteryType": "Smart Multi-Stage Charger",
    "dimensions": "260 x 160 x 90 mm",
    "weight": "2.8 kg",
    "terminalType": "Clamp Connectors",
    "application": "Cars, SUVs, solar banks, inverter batteries",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "isFeatured": true,
    "sku": "EM-ACC-001",
    "description": "Smart multi-stage charging for 12V and 24V batteries. Automatic voltage detection, reverse-polarity protection and desulfation mode to revive tired batteries.",
    "id": "em-accessories-001",
    "inStock": true,
    "isPublished": true,
    "images": [
      "/images/prod-acc-1.jpg",
      "/images/prod-acc-2.jpg"
    ]
  },
  {
    "slug": "energy-man-heavy-duty-500a-jumper-cables",
    "name": "ENERGY MAN Heavy-Duty 500A Jumper Cables",
    "brand": "ENERGY MAN",
    "model": "EM-JMP-500",
    "category": "accessories",
    "subcategory": "Jumper Cables",
    "price": 15000,
    "discountPrice": 13500,
    "voltage": "12V/24V",
    "capacity": "500A Rated",
    "batteryType": "Copper-Clad Aluminium Cables",
    "dimensions": "3.0 metre length",
    "weight": "2.2 kg",
    "terminalType": "Insulated Clamps",
    "application": "Cars, SUVs, vans, generators",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-002",
    "description": "Industrial-grade 500A booster cables with heavy insulated clamps. A must-have in every Lagos boot — jump-start in minutes.",
    "id": "em-accessories-002",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-acc-2.jpg",
      "/images/cat-accessories.jpg"
    ]
  },
  {
    "slug": "solid-brass-heavy-duty-battery-terminal-clamps",
    "name": "Solid Brass Heavy-Duty Battery Terminal Clamps",
    "brand": "ENERGY MAN",
    "model": "EM-TRM-BR",
    "category": "accessories",
    "subcategory": "Terminals & Clamps",
    "price": 8500,
    "discountPrice": 7500,
    "voltage": "Universal",
    "capacity": "Positive & Negative Pair",
    "batteryType": "Solid Brass",
    "dimensions": "Standard Post Fit",
    "weight": "0.4 kg",
    "terminalType": "Bolt-On",
    "application": "All car and inverter batteries",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-003",
    "description": "Solid brass terminal clamps for maximum conductivity and corrosion resistance. Improved cranking and cleaner connections.",
    "id": "em-accessories-003",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-accessories.jpg",
      "/images/prod-acc-1.jpg"
    ]
  },
  {
    "slug": "energy-man-digital-battery-system-analyzer",
    "name": "ENERGY MAN Digital Battery & System Analyzer",
    "brand": "ENERGY MAN",
    "model": "EM-TST-100",
    "category": "accessories",
    "subcategory": "Testers",
    "price": 35000,
    "discountPrice": 32000,
    "voltage": "12V",
    "capacity": "100-2000 CCA Test Range",
    "batteryType": "Digital Analyzer",
    "dimensions": "180 x 90 x 30 mm",
    "weight": "0.5 kg",
    "terminalType": "Clamp Connectors",
    "application": "Workshops, fleets, battery dealers",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-004",
    "description": "Professional digital tester that reads battery health, CCA, state of charge and charging system output in seconds. Fleet-grade accuracy.",
    "id": "em-accessories-004",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-acc-1.jpg",
      "/images/prod-acc-2.jpg"
    ]
  },
  {
    "slug": "energy-man-12v-smart-trickle-charger",
    "name": "ENERGY MAN 12V Smart Trickle Charger & Maintainer",
    "brand": "ENERGY MAN",
    "model": "EM-CHG-12-5",
    "category": "accessories",
    "subcategory": "Chargers",
    "price": 18000,
    "discountPrice": 16500,
    "voltage": "12V",
    "capacity": "5A Output",
    "batteryType": "Smart Float Charger",
    "dimensions": "150 x 80 x 55 mm",
    "weight": "0.9 kg",
    "terminalType": "Clamp & Ring Connectors",
    "application": "Parked cars, motorcycles, standby generators",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-005",
    "description": "Keep parked vehicles and standby generators ready to start. Safe float charging never overcharges — connect and forget.",
    "id": "em-accessories-005",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-acc-2.jpg",
      "/images/cat-accessories.jpg"
    ]
  },
  {
    "slug": "energy-man-battery-isolator-200a",
    "name": "ENERGY MAN Battery Isolator Switch 200A",
    "brand": "ENERGY MAN",
    "model": "EM-ISO-200",
    "category": "accessories",
    "subcategory": "Terminals & Clamps",
    "price": 22000,
    "voltage": "12V/24V",
    "capacity": "200A Rated",
    "batteryType": "Rotary Isolator Switch",
    "dimensions": "90 x 90 x 60 mm",
    "weight": "0.7 kg",
    "terminalType": "Bolt-On Copper Posts",
    "application": "Fleets, buses, trucks, marine, solar banks",
    "warranty": "12 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-006",
    "description": "Heavy-duty battery isolation switch for fleet and solar installations. Cut battery power instantly for maintenance, storage or safety.",
    "id": "em-accessories-006",
    "discountPrice": null,
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/cat-accessories.jpg",
      "/images/prod-acc-1.jpg"
    ]
  },
  {
    "slug": "energy-man-battery-care-kit",
    "name": "ENERGY MAN Battery Carry Strap & Post Cleaner Kit",
    "brand": "ENERGY MAN",
    "model": "EM-KIT-CARE",
    "category": "accessories",
    "subcategory": "Care & Maintenance",
    "price": 5500,
    "discountPrice": 4800,
    "voltage": "Universal",
    "capacity": "—",
    "batteryType": "Accessory Kit",
    "dimensions": "—",
    "weight": "0.6 kg",
    "terminalType": "—",
    "application": "All lead-acid batteries",
    "warranty": "6 Months",
    "manufacturer": "ENERGY MAN Corp",
    "countryOfOrigin": "South Korea",
    "sku": "EM-ACC-007",
    "description": "Practical battery care kit — heavy-duty carry strap plus dual-brush post cleaner. Makes carrying and servicing batteries safe and easy.",
    "id": "em-accessories-007",
    "inStock": true,
    "isFeatured": false,
    "isPublished": true,
    "images": [
      "/images/prod-acc-1.jpg",
      "/images/prod-acc-2.jpg"
    ]
  }
];
