import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding POWERMAN database...');

  // Clean existing tables
  await prisma.enquiry.deleteMany();
  await prisma.product.deleteMany();
  await prisma.siteContent.deleteMany();

  // Initialize Site Content
  await prisma.siteContent.create({
    data: {
      id: 'default',
      phone: '+234 800 123 4567',
      whatsapp: '+234 800 123 4567',
      email: 'info@powermanbatteries.com',
      address: 'Lagos, Nigeria — full address coming soon',
      businessHours: 'Monday – Saturday: 8:00 AM – 6:00 PM',
      promoBannerText: 'POWER YOUR JOURNEY — High-performance automotive, solar, inverter & lithium batteries with nationwide delivery.',
      promoBannerEnabled: true,
      heroHeadline: 'Reliable Power Starts With the Right Battery.',
      heroSubheadline: 'Discover quality batteries and power solutions for vehicles, solar systems, inverters, businesses and everyday power needs.',
      aboutText: 'At POWERMAN, we believe reliable power starts with the right battery. We are a battery sales and distribution company providing a wide range of power solutions for vehicles, solar systems, inverters, businesses and other applications.',
      missionText: 'To provide dependable battery and energy-storage solutions while making it simple for customers to find the right power product for their needs.',
      visionText: 'To become a trusted and recognized name in battery sales and power solutions, known for quality products, professional service and customer satisfaction.',
    },
  });

  const products = [
    // 1. AUTOMOTIVE
    {
      name: 'POWERMAN Pro 75Ah Maintenance-Free Car Battery',
      slug: 'powerman-pro-75ah-car-battery',
      brand: 'POWERMAN',
      model: 'PM-AUTO-75MF',
      category: 'automotive',
      subcategory: 'Car Batteries',
      price: 68000,
      discountPrice: 62000,
      inStock: true,
      voltage: '12V',
      capacity: '75Ah',
      cca: '650 CCA',
      batteryType: 'Sealed Maintenance-Free (Calcium-Calcium)',
      dimensions: '278 x 175 x 190 mm',
      weight: '17.8 kg',
      terminalType: 'Standard DIN Terminal (A)',
      application: 'Sedans, SUVs, Toyota Camry, Honda Accord, Lexus RX, Hyundai Sonata',
      warranty: '12 Months',
      compatibilityNotes: 'Fits most Japanese, Korean and European passenger vehicles requiring 65-75Ah capacity.',
      manufacturer: 'POWERMAN Energy Corp',
      countryOfOrigin: 'South Korea',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-AUTO-001',
      description: 'The POWERMAN Pro 75Ah delivers high cold-cranking power and long service life engineered specifically for Nigerian road and weather conditions. Features sealed maintenance-free design, heavy-duty lead grid plates, and built-in magic-eye state-of-charge indicator.',
      images: JSON.stringify(['/images/prod-auto-1.jpg', '/images/prod-auto-2.jpg']),
    },
    {
      name: 'POWERMAN Heavy-Start 100Ah SUV & Commercial Battery',
      slug: 'powerman-heavy-start-100ah-suv-battery',
      brand: 'POWERMAN',
      model: 'PM-AUTO-100MF',
      category: 'automotive',
      subcategory: 'SUV Batteries',
      price: 95000,
      discountPrice: null,
      inStock: true,
      voltage: '12V',
      capacity: '100Ah',
      cca: '820 CCA',
      batteryType: 'Sealed Maintenance-Free Lead Acid',
      dimensions: '353 x 175 x 190 mm',
      weight: '23.5 kg',
      terminalType: 'Standard SAE Post',
      application: 'Toyota Land Cruiser, Prado, Hilux, Ford Ranger, Mercedes G-Class, Commercial Vans',
      warranty: '12 Months',
      compatibilityNotes: 'Designed for heavy power demands, big V6/V8 diesel and petrol engines, and vehicles with high electronic accessories.',
      manufacturer: 'POWERMAN Energy Corp',
      countryOfOrigin: 'South Korea',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-AUTO-002',
      description: 'Engineered for high-power SUVs, pick-up trucks, and light commercial vans. Provides maximum reserve capacity for extra lights, sound systems, and air conditioning equipment.',
      images: JSON.stringify(['/images/prod-auto-2.jpg', '/images/prod-auto-1.jpg']),
    },
    {
      name: 'Chloride Exide Ultra 60Ah Passenger Car Battery',
      slug: 'chloride-exide-ultra-60ah-car-battery',
      brand: 'Chloride Exide',
      model: 'CE-60MF-L',
      category: 'automotive',
      subcategory: 'Car Batteries',
      price: 55000,
      discountPrice: 51000,
      inStock: true,
      voltage: '12V',
      capacity: '60Ah',
      cca: '510 CCA',
      batteryType: 'Sealed Calcium',
      dimensions: '242 x 175 x 190 mm',
      weight: '14.2 kg',
      terminalType: 'Standard DIN',
      application: 'Compact Cars, Hatchbacks, Toyota Corolla, Honda Civic, Kia Rio',
      warranty: '12 Months',
      compatibilityNotes: 'Ideal for 1.3L to 2.0L engines.',
      manufacturer: 'Chloride Exide',
      countryOfOrigin: 'Kenya',
      isFeatured: false,
      isPublished: true,
      sku: 'CE-AUTO-003',
      description: 'Popular trusted automotive battery providing dependable instant starting in tropical climates with minimal self-discharge.',
      images: JSON.stringify(['/images/cat-automotive.jpg']),
    },
    {
      name: 'POWERMAN Start-Stop AGM 80Ah Battery',
      slug: 'powerman-start-stop-agm-80ah-battery',
      brand: 'POWERMAN',
      model: 'PM-AGM-80',
      category: 'automotive',
      subcategory: 'Start-Stop Batteries',
      price: 145000,
      discountPrice: 138000,
      inStock: true,
      voltage: '12V',
      capacity: '80Ah',
      cca: '800 CCA',
      batteryType: 'Absorbent Glass Mat (AGM)',
      dimensions: '315 x 175 x 190 mm',
      weight: '22.0 kg',
      terminalType: 'Standard DIN Post',
      application: 'BMW 3/5 Series, Mercedes C/E Class, Audi A4/A6, Range Rover, Modern Start-Stop vehicles',
      warranty: '18 Months',
      compatibilityNotes: 'Mandatory replacement for micro-hybrid and start-stop vehicles.',
      manufacturer: 'POWERMAN Germany',
      countryOfOrigin: 'Germany',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-AGM-004',
      description: 'Premium AGM battery with 3x cycle life compared to conventional batteries. Engineered for luxury cars equipped with automatic start-stop technology and intensive power regeneration.',
      images: JSON.stringify(['/images/prod-auto-1.jpg']),
    },

    // 2. MOTORCYCLE
    {
      name: 'POWERMAN Rider YTX9-BS 12V 9Ah Motorcycle Battery',
      slug: 'powerman-rider-ytx9-bs-motorcycle-battery',
      brand: 'POWERMAN',
      model: 'PM-MOTO-YTX9',
      category: 'motorcycle',
      subcategory: 'Motorcycle Batteries',
      price: 28000,
      discountPrice: null,
      inStock: true,
      voltage: '12V',
      capacity: '9Ah',
      cca: '135 CCA',
      batteryType: 'Sealed AGM Gel Maintenance Free',
      dimensions: '150 x 87 x 105 mm',
      weight: '3.1 kg',
      terminalType: 'M6 Nut & Bolt',
      application: 'Sports Bikes, Cruisers, Honda, Yamaha, Bajaj Pulsar, TVS Apache',
      warranty: '6 Months',
      compatibilityNotes: 'Pre-charged, leak-proof AGM spill-proof design.',
      manufacturer: 'POWERMAN Moto Tech',
      countryOfOrigin: 'Vietnam',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-MOTO-001',
      description: 'Vibration-resistant high-performance motorcycle battery with fast cranking amps and long storage life without power drop.',
      images: JSON.stringify(['/images/cat-motorcycle.jpg']),
    },
    {
      name: 'POWERMAN Heavy-Duty 12V 14Ah Tricycle (Keke) Battery',
      slug: 'powerman-12v-14ah-tricycle-keke-battery',
      brand: 'POWERMAN',
      model: 'PM-KEKE-14Ah',
      category: 'motorcycle',
      subcategory: 'Tricycle Batteries',
      price: 38000,
      discountPrice: 35000,
      inStock: true,
      voltage: '12V',
      capacity: '14Ah',
      cca: '190 CCA',
      batteryType: 'Heavy Duty Sealed Lead Acid',
      dimensions: '134 x 89 x 166 mm',
      weight: '4.5 kg',
      terminalType: 'Brass Stud Terminal',
      application: 'Commercial Tricycles (Keke Napep), TVS King, Bajaj RE, Piaggio',
      warranty: '6 Months',
      compatibilityNotes: 'Specially built for frequent daily engine starts and heavy transport use.',
      manufacturer: 'POWERMAN Moto Tech',
      countryOfOrigin: 'India',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-MOTO-002',
      description: 'Reinforced casing and thick grid plates engineered for daily commercial commercial tricycle operations under high heat and heavy vibration.',
      images: JSON.stringify(['/images/cat-motorcycle.jpg']),
    },

    // 3. TRUCK & HEAVY-DUTY
    {
      name: 'POWERMAN Titan 150Ah Commercial Truck Battery',
      slug: 'powerman-titan-150ah-truck-battery',
      brand: 'POWERMAN',
      model: 'PM-TRUCK-150',
      category: 'truck',
      subcategory: 'Commercial Vehicle Batteries',
      price: 175000,
      discountPrice: 165000,
      inStock: true,
      voltage: '12V',
      capacity: '150Ah',
      cca: '1050 CCA',
      batteryType: 'Heavy-Duty Low Maintenance Hybrid Lead-Acid',
      dimensions: '513 x 189 x 223 mm',
      weight: '41.0 kg',
      terminalType: 'Tapered SAE Post',
      application: 'Mack Trucks, HOWO Tipper, Mercedes Actros, Commercial Buses, Haulage Trailers',
      warranty: '12 Months',
      compatibilityNotes: 'Dual 12V setup for 24V starter heavy truck systems.',
      manufacturer: 'POWERMAN Heavy Duty',
      countryOfOrigin: 'Turkey',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-TRK-001',
      description: 'Heavy industrial power designed for interstate transport haulage trucks and trailers. Resists extreme road vibrations and intense heat.',
      images: JSON.stringify(['/images/prod-truck-1.jpg', '/images/cat-truck.jpg']),
    },
    {
      name: 'POWERMAN Titan Max 200Ah Heavy Machinery Battery',
      slug: 'powerman-titan-max-200ah-heavy-machinery-battery',
      brand: 'POWERMAN',
      model: 'PM-TRUCK-200',
      category: 'truck',
      subcategory: 'Heavy Equipment Batteries',
      price: 230000,
      discountPrice: null,
      inStock: true,
      voltage: '12V',
      capacity: '200Ah',
      cca: '1300 CCA',
      batteryType: 'Reinforced Deep Crank Commercial Battery',
      dimensions: '518 x 276 x 242 mm',
      weight: '56.0 kg',
      terminalType: 'Heavy Duty Threaded / SAE Dual',
      application: 'CAT Excavators, Bulldozers, Heavy Diesel Generators, Agricultural Tractors, Large Buses',
      warranty: '12 Months',
      compatibilityNotes: 'Maximum cranking power for massive diesel engines.',
      manufacturer: 'POWERMAN Heavy Duty',
      countryOfOrigin: 'Turkey',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-TRK-002',
      description: 'Our largest capacity 12V lead-acid starter battery built for construction site equipment, mining tractors, and prime power industrial generators.',
      images: JSON.stringify(['/images/cat-truck.jpg']),
    },

    // 4. SOLAR
    {
      name: 'POWERMAN SolarPro 220Ah 12V Tall Tubular Solar Battery',
      slug: 'powerman-solarpro-220ah-tall-tubular-battery',
      brand: 'POWERMAN',
      model: 'PM-SOLAR-220TT',
      category: 'solar',
      subcategory: 'Tubular Batteries',
      price: 240000,
      discountPrice: 225000,
      inStock: true,
      voltage: '12V',
      capacity: '220Ah @ C20',
      cca: 'N/A (Deep Cycle)',
      batteryType: 'Tall Tubular Deep-Cycle Lead Acid',
      dimensions: '505 x 190 x 410 mm',
      weight: '62.5 kg',
      terminalType: 'M8 L-Terminal Bolt',
      application: 'Off-Grid Solar Systems, Residential Backup, Commercial Solar Systems',
      warranty: '24 Months',
      compatibilityNotes: 'Optimized for deep discharge cycles up to 80% DOD. Expected lifespan 5+ years with proper maintenance.',
      manufacturer: 'POWERMAN Solar Tech',
      countryOfOrigin: 'India',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-SOL-001',
      description: 'Industry standard for Nigerian residential solar installations. Tall tubular positive plates ensure long cycle life, high temperature resistance, and fast solar recharge acceptance.',
      images: JSON.stringify(['/images/prod-solar-1.jpg', '/images/cat-solar.jpg']),
    },
    {
      name: 'Sonnenschein Solar Gel 200Ah 12V Deep-Cycle Battery',
      slug: 'sonnenschein-solar-gel-200ah-battery',
      brand: 'Sonnenschein',
      model: 'SNG-GEL-200',
      category: 'solar',
      subcategory: 'Gel Batteries',
      price: 260000,
      discountPrice: 248000,
      inStock: true,
      voltage: '12V',
      capacity: '200Ah',
      cca: 'N/A (Deep Cycle)',
      batteryType: 'Dryfit Gel Sealed Maintenance-Free',
      dimensions: '522 x 240 x 219 mm',
      weight: '60.0 kg',
      terminalType: 'M8 Female Thread',
      application: 'Solar Inverter Systems, Telecom Sites, Medical Equipment, Remote Cabins',
      warranty: '24 Months',
      compatibilityNotes: 'Zero maintenance required. Absolutely non-gassing and leakproof.',
      manufacturer: 'Sonnenschein Germany',
      countryOfOrigin: 'Germany',
      isFeatured: true,
      isPublished: true,
      sku: 'SNG-SOL-002',
      description: 'German-engineered gel battery providing outstanding deep-discharge capability and superior performance under elevated tropical ambient temperatures.',
      images: JSON.stringify(['/images/cat-solar.jpg']),
    },

    // 5. INVERTER
    {
      name: 'POWERMAN PowerBank 220Ah Tubular Inverter Battery',
      slug: 'powerman-powerbank-220ah-tubular-inverter-battery',
      brand: 'POWERMAN',
      model: 'PM-INV-220TT',
      category: 'inverter',
      subcategory: 'Tubular Inverter Batteries',
      price: 235000,
      discountPrice: 220000,
      inStock: true,
      voltage: '12V',
      capacity: '220Ah',
      cca: 'N/A (Deep Cycle)',
      batteryType: 'Tall Tubular Technology',
      dimensions: '505 x 190 x 410 mm',
      weight: '61.0 kg',
      terminalType: 'Heavy Duty Lead Terminal Nut & Bolt',
      application: 'Home Inverters, Office Backups, Luminous/Felicity/Prag Inverters (1.5kVA – 10kVA)',
      warranty: '24 Months',
      compatibilityNotes: 'Works seamlessly with pure sine wave and modified sine wave inverters.',
      manufacturer: 'POWERMAN Inverter Solutions',
      countryOfOrigin: 'India',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-INV-001',
      description: 'Specially engineered for long power outage backup hours in Nigerian homes and offices. High electrolyte volume ensures minimal topping up.',
      images: JSON.stringify(['/images/prod-inverter-1.jpg', '/images/cat-inverter.jpg']),
    },
    {
      name: 'Exide Inva Tubular 200Ah Heavy Backup Inverter Battery',
      slug: 'exide-inva-tubular-200ah-inverter-battery',
      brand: 'Exide',
      model: 'IT-500-200Ah',
      category: 'inverter',
      subcategory: 'Tubular Inverter Batteries',
      price: 225000,
      discountPrice: null,
      inStock: true,
      voltage: '12V',
      capacity: '200Ah',
      cca: 'N/A (Deep Cycle)',
      batteryType: 'Tubular Positive Plate Lead-Acid',
      dimensions: '500 x 187 x 416 mm',
      weight: '58.0 kg',
      terminalType: 'M8 Terminal',
      application: 'Home and Commercial Inverter Systems',
      warranty: '18 Months',
      compatibilityNotes: 'Proven durability with fast recharge capability after deep discharge.',
      manufacturer: 'Exide Industries',
      countryOfOrigin: 'India',
      isFeatured: false,
      isPublished: true,
      sku: 'EXI-INV-002',
      description: 'Renowned high-performance inverter battery featuring spine alloy technology that resists corrosion and prolongs battery lifespan.',
      images: JSON.stringify(['/images/cat-inverter.jpg']),
    },

    // 6. LITHIUM
    {
      name: 'POWERMAN LiFePO4 48V 100Ah (5.12kWh) Wall-Mount Lithium Battery',
      slug: 'powerman-lifepo4-48v-100ah-5-12kwh-wall-mount-lithium-battery',
      brand: 'POWERMAN',
      model: 'PM-LFP-48100WM',
      category: 'lithium',
      subcategory: 'Lithium Solar / Inverter',
      price: 850000,
      discountPrice: 790000,
      inStock: true,
      voltage: '51.2V (48V Nominal)',
      capacity: '100Ah (5.12kWh)',
      cca: 'N/A (Smart BMS)',
      batteryType: 'Lithium Iron Phosphate (LiFePO4)',
      dimensions: '680 x 480 x 180 mm',
      weight: '46.0 kg',
      terminalType: 'M8 High Current Screw Terminal + CAN/RS485 Bus',
      application: 'Solar Systems, Hybrid Inverters (Deye, Growatt, Victron, Felicity, Must)',
      warranty: '60 Months (5 Years)',
      compatibilityNotes: '6000+ cycles @ 80% DOD. Integrated Smart BMS with LCD touchscreen status display.',
      manufacturer: 'POWERMAN Energy Tech',
      countryOfOrigin: 'China / Germany Joint Venture',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-LTH-001',
      description: 'Next-generation wall-mounted lithium energy storage system. Designed for 15+ years service life with zero maintenance, ultra-fast charging capability (0.5C to 1C), and smart communication port with all major inverter brands.',
      images: JSON.stringify(['/images/prod-lithium-1.jpg', '/images/cat-lithium.jpg']),
    },
    {
      name: 'POWERMAN LiFePO4 12.8V 100Ah Lithium Battery',
      slug: 'powerman-lifepo4-12v-100ah-lithium-battery',
      brand: 'POWERMAN',
      model: 'PM-LFP-12100',
      category: 'lithium',
      subcategory: 'Backup Power',
      price: 290000,
      discountPrice: 275000,
      inStock: true,
      voltage: '12.8V',
      capacity: '100Ah (1280Wh)',
      cca: 'N/A (BMS Protected)',
      batteryType: 'Lithium Iron Phosphate (LiFePO4)',
      dimensions: '330 x 172 x 215 mm',
      weight: '11.5 kg',
      terminalType: 'M8 Threaded Bolt',
      application: 'Drop-in lead-acid replacement for 12V Inverters, Solar, Marine, Campers',
      warranty: '36 Months',
      compatibilityNotes: 'Weighs 1/3 of a standard 100Ah lead battery with 10x longer lifespan (3000+ cycles).',
      manufacturer: 'POWERMAN Energy Tech',
      countryOfOrigin: 'China',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-LTH-002',
      description: 'Direct lightweight replacement for lead-acid 12V batteries. Provides constant power output throughout discharge with built-in protection against short-circuit, over-charge, and temperature.',
      images: JSON.stringify(['/images/prod-lithium-1.jpg']),
    },

    // 7. INDUSTRIAL & UPS
    {
      name: 'POWERMAN Telecom 12V 100Ah Front Terminal AGM Battery',
      slug: 'powerman-telecom-12v-100ah-front-terminal-battery',
      brand: 'POWERMAN',
      model: 'PM-FT-12100',
      category: 'industrial',
      subcategory: 'Telecom Batteries',
      price: 130000,
      discountPrice: null,
      inStock: true,
      voltage: '12V',
      capacity: '100Ah',
      cca: 'N/A',
      batteryType: 'Front Terminal AGM VRLA',
      dimensions: '508 x 110 x 223 mm',
      weight: '31.0 kg',
      terminalType: 'M8 Front Access Terminal',
      application: '19" & 23" Telecom Cabinets, Server Racks, Datacenters, Substation Backup',
      warranty: '12 Months',
      compatibilityNotes: 'Compact front terminal design for quick installation in standard equipment racks.',
      manufacturer: 'POWERMAN Industrial',
      countryOfOrigin: 'Vietnam',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-IND-001',
      description: 'Specialized front-access AGM battery engineered for telecom base stations, internet server racks, and high-density industrial power backup systems.',
      images: JSON.stringify(['/images/cat-industrial.jpg']),
    },
    {
      name: 'POWERMAN High-Rate UPS 12V 12Ah Sealed Lead Battery',
      slug: 'powerman-ups-12v-12ah-sealed-battery',
      brand: 'POWERMAN',
      model: 'PM-UPS-1212',
      category: 'industrial',
      subcategory: 'UPS Batteries',
      price: 22000,
      discountPrice: 19500,
      inStock: true,
      voltage: '12V',
      capacity: '12Ah',
      cca: 'N/A',
      batteryType: 'Sealed Lead Acid (VRLA)',
      dimensions: '151 x 98 x 95 mm',
      weight: '3.6 kg',
      terminalType: 'F2 Terminal (6.35mm)',
      application: 'Desktop Computer UPS (APC, Mercury, Bluegate), Alarm Systems, Gate Motors',
      warranty: '6 Months',
      compatibilityNotes: 'Fits standard desktop power backup UPS units.',
      manufacturer: 'POWERMAN Industrial',
      countryOfOrigin: 'China',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-IND-002',
      description: 'Reliable rechargeable sealed lead-acid battery designed for high discharge current requirements in computer UPS backup power supply units.',
      images: JSON.stringify(['/images/cat-industrial.jpg']),
    },

    // 8. ACCESSORIES
    {
      name: 'POWERMAN Intelligent 12V/24V 20A Smart Battery Charger & Desulfator',
      slug: 'powerman-intelligent-12v-24v-20a-smart-charger',
      brand: 'POWERMAN',
      model: 'PM-CHG-20A',
      category: 'accessories',
      subcategory: 'Battery Chargers',
      price: 42000,
      discountPrice: 38000,
      inStock: true,
      voltage: '12V / 24V Auto Select',
      capacity: 'For batteries from 20Ah to 300Ah',
      cca: 'N/A',
      batteryType: 'Compatible with Lead-Acid, AGM, Gel, Calcium, and LiFePO4',
      dimensions: '220 x 130 x 70 mm',
      weight: '1.4 kg',
      terminalType: 'Heavy-Duty Insulated Alligator Clamps',
      application: 'Cars, Trucks, Solar/Inverter Battery Maintenance, Garage Repair Shops',
      warranty: '12 Months',
      compatibilityNotes: 'Features 7-stage automatic charging cycle and pulse repair desulfation mode.',
      manufacturer: 'POWERMAN Electronics',
      countryOfOrigin: 'Taiwan',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-ACC-001',
      description: 'Microprocessor-controlled smart battery charger and pulse repairer. Restores old/sulfated batteries, prevents overcharging, and displays real-time voltage, current, and temperature on an LCD screen.',
      images: JSON.stringify(['/images/prod-acc-1.jpg', '/images/cat-accessories.jpg']),
    },
    {
      name: 'POWERMAN Heavy-Duty 500A Pure Copper Jumper Booster Cables (4 Metres)',
      slug: 'powerman-heavy-duty-500a-jumper-cables-4m',
      brand: 'POWERMAN',
      model: 'PM-CABLE-500A',
      category: 'accessories',
      subcategory: 'Battery Cables',
      price: 25000,
      discountPrice: null,
      inStock: true,
      voltage: '12V / 24V',
      capacity: '500 Amps Peak',
      cca: 'N/A',
      batteryType: 'All Automotive & Truck Batteries',
      dimensions: '4.0 Metres length',
      weight: '2.8 kg',
      terminalType: 'Heavy PVC Coated Copper Clamps',
      application: 'Emergency jump starting for cars, SUVs, trucks, and buses',
      warranty: '12 Months',
      compatibilityNotes: 'Tangle-free rubber insulation stays flexible even in cold conditions.',
      manufacturer: 'POWERMAN Tools',
      countryOfOrigin: 'China',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-ACC-002',
      description: 'Professional grade 100% thick copper core booster cables with heavy spring-loaded color-coded clamps. Essential emergency equipment for every vehicle owner.',
      images: JSON.stringify(['/images/cat-accessories.jpg']),
    },
    {
      name: 'Solid Brass Heavy-Duty Battery Terminal Clamps (Pair)',
      slug: 'solid-brass-heavy-duty-battery-terminal-clamps-pair',
      brand: 'POWERMAN',
      model: 'PM-TERM-BRASS',
      category: 'accessories',
      subcategory: 'Battery Terminals',
      price: 8500,
      discountPrice: null,
      inStock: true,
      voltage: 'Universal',
      capacity: 'Universal',
      cca: 'N/A',
      batteryType: 'Top Post Batteries',
      dimensions: 'Standard Post Fitting',
      weight: '0.3 kg5',
      terminalType: 'Solid Brass Bolt Clamp',
      application: 'Automotive, Marine, Solar and Inverter Battery Cable Termination',
      warranty: '24 Months',
      compatibilityNotes: 'Resists corrosion, delivers maximum current conductivity.',
      manufacturer: 'POWERMAN Accessories',
      countryOfOrigin: 'India',
      isFeatured: false,
      isPublished: true,
      sku: 'PM-ACC-003',
      description: 'High conductivity forged brass battery terminal connectors with stainless steel bolts for positive and negative battery posts. Prevents acid corrosion and power resistance.',
      images: JSON.stringify(['/images/cat-accessories.jpg']),
    },
    {
      name: 'POWERMAN Digital Automotive & Deep Cycle Battery System Tester',
      slug: 'powerman-digital-battery-system-tester',
      brand: 'POWERMAN',
      model: 'PM-TST-100',
      category: 'accessories',
      subcategory: 'Battery Testers',
      price: 35000,
      discountPrice: 32000,
      inStock: true,
      voltage: '12V / 24V',
      capacity: '100 - 2000 CCA testing range',
      cca: 'Supports CCA, EN, IEC, DIN, SAE standards',
      batteryType: 'Lead Acid, AGM, Gel, EFB',
      dimensions: '150 x 85 x 25 mm',
      weight: '0.4 kg',
      terminalType: 'Kelvin Test Clamps',
      application: 'Mechanics, Battery Retailers, Solar Installers, Fleet Maintenance',
      warranty: '12 Months',
      compatibilityNotes: 'Tests battery health %, internal resistance (mΩ), cranking capability, and alternator charging system performance.',
      manufacturer: 'POWERMAN Electronics',
      countryOfOrigin: 'Taiwan',
      isFeatured: true,
      isPublished: true,
      sku: 'PM-ACC-004',
      description: 'Professional handheld digital battery analyzer. Provides accurate instant diagnostics of battery health (SOH), state of charge (SOC), internal resistance, and starter/alternator health.',
      images: JSON.stringify(['/images/prod-acc-1.jpg']),
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  // Sample Enquiries
  await prisma.enquiry.createMany({
    data: [
      {
        name: 'Emeka Okonkwo',
        phone: '+234 802 345 6789',
        whatsapp: '+234 802 345 6789',
        email: 'emeka.o@gmail.com',
        productSlug: 'powerman-pro-75ah-car-battery',
        productName: 'POWERMAN Pro 75Ah Maintenance-Free Car Battery',
        quantity: 1,
        location: 'Ikeja, Lagos',
        preferredDelivery: 'Home/Office Delivery',
        message: 'Hello, I want to know if this battery fits a 2018 Toyota Camry and how fast you can deliver to Ikeja.',
        source: 'product_page',
        status: 'New',
      },
      {
        name: 'Fatima Bello',
        phone: '+234 813 987 6543',
        whatsapp: '+234 813 987 6543',
        email: 'fatima.bello@yahoo.com',
        productSlug: 'powerman-solarpro-220ah-tall-tubular-battery',
        productName: 'POWERMAN SolarPro 220Ah 12V Tall Tubular Solar Battery',
        quantity: 4,
        location: 'Lekki Phase 1, Lagos',
        preferredDelivery: 'Home/Office Delivery',
        message: 'I am installing a 3.5kVA solar system and need 4 units of 220Ah tubular batteries. Please send me a quote including delivery.',
        source: 'order_modal',
        status: 'Contacted',
      },
      {
        name: 'Babajide Adeleke',
        phone: '+234 805 112 2334',
        whatsapp: '+234 805 112 2334',
        email: 'adeleke.b@company.ng',
        productSlug: null,
        productName: null,
        quantity: 1,
        location: 'Victoria Island, Lagos',
        preferredDelivery: 'Pickup',
        message: 'We require a bulk quote for 10 units of 200Ah AGM batteries for our office backup inverter setup.',
        source: 'contact_form',
        status: 'Awaiting Customer',
      },
    ],
  });

  console.log(`Database seeded successfully with ${products.length} products and sample enquiries.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('Error during seed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
